# Generated by Django 4.0.4 on 2023-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_reports_total_move_reports_total_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsparts',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='reportsrecords',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания ремонта'),
        ),
    ]
