# Generated by Django 4.0.4 on 2023-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_reportsparts_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsrecords',
            name='order_parts',
            field=models.BooleanField(default=False, verbose_name='Запчасти заказаны'),
        ),
    ]
