# Generated by Django 4.0.4 on 2023-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_reportsrecords_order_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsparts',
            name='send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='reportsparts',
            name='send_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер РПО'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('send', 'отправлен на проверку'), ('refinement', 'на доработке'), ('received', 'идет проверка'), ('verified', 'проверка закончена'), ('accepted', 'принят'), ('payment', 'передан в оплату')], default='draft', max_length=100, verbose_name='Статус'),
        ),
    ]
