# Generated by Django 4.0.4 on 2023-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_reportsparts_send_date_reportsparts_send_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsrecords',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания ремонта'),
        ),
    ]
