# Generated by Django 4.0.4 on 2023-06-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_reportsrecords_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='act',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='mail_date',
        ),
        migrations.AddField(
            model_name='reports',
            name='send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
    ]
