# Generated by Django 4.0.4 on 2023-04-15 14:27

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0022_alter_reportsrecords_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocumnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('act', 'Акт'), ('invoice', 'Счет'), ('netting', 'Акт взаимозачета'), ('other', 'Другое')], max_length=20, verbose_name='Наименование документа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('file', models.FileField(upload_to=upload.models.document_name, verbose_name='Файйл документа')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Документ отчета',
                'verbose_name_plural': 'Документы отчетов',
                'ordering': ['report', 'title'],
            },
        ),
    ]
