# Generated by Django 4.0.4 on 2023-05-21 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_alter_reportsrecords_end_date'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdocumnent',
            name='file',
            field=models.FileField(upload_to=upload.models.document_name, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', '+xls'])], verbose_name='Файйл документа'),
        ),
        migrations.CreateModel(
            name='RecordDocumnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('file', models.FileField(upload_to=upload.models.document_name, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', '+xls'])], verbose_name='Файйл документа')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportsrecords', verbose_name='Ремонт')),
            ],
            options={
                'verbose_name': 'Документ ремонта',
                'verbose_name_plural': 'Документы ремонта',
                'ordering': ['record', 'title'],
            },
        ),
    ]
